apiVersion: v1
kind: Namespace
metadata:
  name: user-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: 260956700310.dkr.ecr.ap-northeast-2.amazonaws.com/user-service:latest
          ports:
            - containerPort: 8081

          envFrom:
            - secretRef:
                name: bari-app-secrets      # DB_*, JWT_SECRET 등 민감값
            - configMapRef:
                name: bari-app-config       # SPRING_PROFILES_ACTIVE, JAVA_OPTS, REDIS_HOST, 내부 DNS 주소 등 비민감값

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 20
