# 로컬 개발 환경 설정
# 실행: ./gradlew :services:product-service:bootRun --args='--spring.profiles.active=local'

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mariadb://localhost:3306/bari
    username: bari
    password: bari1234

logging:
  level:
    com.bari: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

# s3 설정 (실제 값 등록 필요)
cloud:
  aws:
    region: ${AWS_REGION:ap-northeast-2}
    credentials:
     access-key: ${AWS_ACCESS_KEY}
     secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: ${AWS_S3_BUCKET:bari-product-images}