apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway-ingress
  namespace: gateway # Ingress가 라우팅할 수 있는 namespace를 지정(api-gateway 서비스가 있는 namespace)
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
spec:
  ingressClassName: alb
  rules: # 무엇을 어디로 보낼지 정의
    - http:
        paths:
          - path: /
            pathType: Prefix  # path + pathType: /로 시작하는 모든 경로
            backend:
              service:
                name: api-gateway # 매칭되는 요청은 backend.service.name: api-gateway, port 80으로 전달
                port:
                  number: 80