apiVersion: v1
kind: Secret
metadata:
  name: discount-service-secret
  namespace: discount-service
type: Opaque
stringData:
  # 내부 서비스 호스트 (k8s ClusterIP DNS)
  PRODUCT_SERVICE_HOST: product-service.product-service.svc.cluster.local
  PRODUCT_SERVICE_PORT: "8083"
  INVENTORY_SERVICE_HOST: inventory-service.inventory-service.svc.cluster.local
  INVENTORY_SERVICE_PORT: "8084"
