apiVersion: v1
kind: Secret
metadata:
  name: inventory-service-secret
  namespace: inventory-service
type: Opaque
stringData:
  # Kafka
  KAFKA_BOOTSTRAP_SERVERS: kafka.kafka.svc.cluster.local:9092

  # 내부 서비스 호스트 (k8s ClusterIP DNS)
  PRODUCT_SERVICE_HOST: product-service.product-service.svc.cluster.local
  PRODUCT_SERVICE_PORT: "8083"
