apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: inventory-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: 260956700310.dkr.ecr.ap-northeast-2.amazonaws.com/inventory-service:latest
          ports:
            - containerPort: 8084
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: inventory-service-secret
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: inventory-service-secret
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: inventory-service-secret
                  key: DB_NAME
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: inventory-service-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: inventory-service-secret
                  key: DB_PASSWORD
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka-service.bari.svc.cluster.local:9092

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 30
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 60
            periodSeconds: 20