apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: 260956700310.dkr.ecr.ap-northeast-2.amazonaws.com/api-gateway:latest
          ports:
            - containerPort: 8080
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: bari-app-secrets
                  key: JWT_SECRET
            - name: STORE_SERVICE_HOST
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: STORE_SERVICE_HOST
            - name: STORE_SERVICE_PORT
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: STORE_SERVICE_PORT
            - name: PRODUCT_SERVICE_HOST
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: PRODUCT_SERVICE_HOST
            - name: PRODUCT_SERVICE_PORT
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: PRODUCT_SERVICE_PORT

            - name: INVENTORY_SERVICE_HOST
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: INVENTORY_SERVICE_HOST
            - name: INVENTORY_SERVICE_PORT
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: INVENTORY_SERVICE_PORT

            - name: USER_SERVICE_HOST
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: USER_SERVICE_HOST
            - name: USER_SERVICE_PORT
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: USER_SERVICE_PORT
            - name: DISCOUNT_SERVICE_HOST
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: DISCOUNT_SERVICE_HOST
            - name: DISCOUNT_SERVICE_PORT
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: DISCOUNT_SERVICE_PORT
            - name: ORDER_SERVICE_HOST
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: ORDER_SERVICE_HOST
            - name: ORDER_SERVICE_PORT
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: ORDER_SERVICE_PORT
