apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: <AWS_ACCOUNT_ID>.dkr.ecr.ap-northeast-2.amazonaws.com/api-gateway:latest
          ports:
            - containerPort: 8080
          env:
            - name: PRODUCT_SERVICE_HOST
              value: product-service.product-service.svc.cluster.local
            - name: PRODUCT_SERVICE_PORT
              value: "8083"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: jwt-secret
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 20