apiVersion: v1
kind: Secret
metadata:
  name: gateway-secret
  namespace: gateway
type: Opaque
stringData:
  PRODUCT_SERVICE_HOST: product-service.product-service.svc.cluster.local
  PRODUCT_SERVICE_PORT: "8083"

  INVENTORY_SERVICE_HOST: inventory-service.inventory-service.svc.cluster.local
  INVENTORY_SERVICE_PORT: "8084"