apiVersion: v1
kind: Secret
metadata:
  name: gateway-secret
  namespace: gateway
type: Opaque
stringData:
  STORE_SERVICE_HOST: store-service.store-service.svc.cluster.local
  STORE_SERVICE_PORT: "8082"

  PRODUCT_SERVICE_HOST: product-service.product-service.svc.cluster.local
  PRODUCT_SERVICE_PORT: "8083"

  INVENTORY_SERVICE_HOST: inventory-service.inventory-service.svc.cluster.local
  INVENTORY_SERVICE_PORT: "8084"

  USER_SERVICE_HOST: user-service.user-service.svc.cluster.local
  USER_SERVICE_PORT: "8081"

  DISCOUNT_SERVICE_HOST: discount-service.discount-service.svc.cluster.local
  DISCOUNT_SERVICE_PORT: "8085"

  ORDER_SERVICE_HOST: order-service.order-service.svc.cluster.local
  ORDER_SERVICE_PORT: "8086"

