apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: 260956700310.dkr.ecr.ap-northeast-2.amazonaws.com/order-service:latest
          ports:
            - containerPort: 8086
          env:
            - name: SERVER_PORT
              value: "8086"
            - name: JAVA_OPTS
              value: "-Xms128m -Xmx256m"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: bari-app-secrets
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: bari-app-secrets
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: bari-app-secrets
                  key: DB_NAME
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: bari-app-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bari-app-secrets
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: bari-app-secrets
                  key: JWT_SECRET
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: order-service-secret
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: STORE_SERVICE_HOST
              valueFrom:
                secretKeyRef:
                  name: order-service-secret
                  key: STORE_SERVICE_HOST
            - name: STORE_SERVICE_PORT
              valueFrom:
                secretKeyRef:
                  name: order-service-secret
                  key: STORE_SERVICE_PORT
            - name: PRODUCT_SERVICE_HOST
              valueFrom:
                secretKeyRef:
                  name: order-service-secret
                  key: PRODUCT_SERVICE_HOST
            - name: PRODUCT_SERVICE_PORT
              valueFrom:
                secretKeyRef:
                  name: order-service-secret
                  key: PRODUCT_SERVICE_PORT
            - name: INVENTORY_SERVICE_HOST
              valueFrom:
                secretKeyRef:
                  name: order-service-secret
                  key: INVENTORY_SERVICE_HOST
            - name: INVENTORY_SERVICE_PORT
              valueFrom:
                secretKeyRef:
                  name: order-service-secret
                  key: INVENTORY_SERVICE_PORT
            - name: DISCOUNT_SERVICE_HOST
              valueFrom:
                secretKeyRef:
                  name: order-service-secret
                  key: DISCOUNT_SERVICE_HOST
            - name: DISCOUNT_SERVICE_PORT
              valueFrom:
                secretKeyRef:
                  name: order-service-secret
                  key: DISCOUNT_SERVICE_PORT
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8086
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8086
            initialDelaySeconds: 60
            periodSeconds: 15
