apiVersion: v1
kind: Secret
metadata:
  name: order-service-secret
  namespace: order-service
type: Opaque
stringData:
  # Kafka
  KAFKA_BOOTSTRAP_SERVERS: kafka.kafka.svc.cluster.local:9092

  # 내부 서비스 호스트 (k8s ClusterIP DNS)
  STORE_SERVICE_HOST: store-service.store-service.svc.cluster.local
  STORE_SERVICE_PORT: "8080"
  PRODUCT_SERVICE_HOST: product-service.product-service.svc.cluster.local
  PRODUCT_SERVICE_PORT: "8080"
  INVENTORY_SERVICE_HOST: inventory-service.inventory-service.svc.cluster.local
  INVENTORY_SERVICE_PORT: "8080"
