apiVersion: v1
kind: Secret
metadata:
  name: store-service-secret 
  namespace: bari            
type: Opaque
stringData:
  DB_HOST: bari.cxwsg8yu0rtk.ap-northeast-2.rds.amazonaws.com
  DB_PORT: "3306"
  DB_NAME: bari
  DB_USERNAME: bari
  DB_PASSWORD: bari1234
  JWT_SECRET: bari-super-secret-key-must-be-at-least-32-chars