name: Deploy product-service

on:    # Trigger 
  push:
    branches: [dev]
    paths:
      - "services/product-service/**"
      - "libs/**"
      - ".github/workflows/deploy-product-service.yml"
      - ".github/workflows/deploy-service.yml"
  workflow_dispatch: {}

concurrency:
  group: deploy-product-service
  cancel-in-progress: false

jobs:  # workflow 안에서 실행되는 작업 단위
  deploy:
    uses: ./.github/workflows/deploy-service.yml
    with:
      service_name: product-service
      namespace: product-service
    secrets: inherit
