name: Deploy api-gateway

on:
  push:
    branches: [dev]
    paths:
      - "services/api-gateway/**"
      - "libs/**"
      - ".github/workflows/deploy-api-gateway.yml"
      - ".github/workflows/deploy-service.yml"
  workflow_dispatch: {} # Actions 탭에서 수동으로도 실행 가능하게

concurrency:
  group: deploy-api-gateway
  cancel-in-progress: false

jobs:
  deploy:
    uses: ./.github/workflows/deploy-service.yml
    with:
      service_name: api-gateway
      namespace: gateway
    secrets: inherit
